version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: chatbet_test_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Test_Password
    ports:
      - "3306:3306"
    
  app:
    build: .
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://mysql:Test_Password@db:3306/chatbet_test_db
    ports:
      - "80:8000"